// LOCALHOST
###
GET http://localhost:8080/recipes
###
GET http://localhost:8080/recipes/61a921f6028954d4f0319e6d
###
GET http://localhost:8080/recipes/61a921f6028954d4f0319e6e
###
GET http://localhost:8080/recipes/61a921f6028954d4f0319e6f


### Create recipe 
POST http://localhost:8080/recipes HTTP/1.1 
content-type: application/json

{
"recipeCategory":"Pasta", "recipeContributer":"Darrell Smith", "recipeName": "Chocolate Cake", "recipeURL":"cookingwithdarrell.com"
}




### PUT recipe which means update
PUT http://localhost:8080/recipes/61a921f6028954d4f0319e6f HTTP/1.1 
content-type: application/json

{
"recipeCategory":"Dessert", "recipeContributer":"Carla", "recipeName":"Chocolate Cookies", "recipeURL":"bestcookiesever.com"
} 
### DELETE recipe 
DELETE http://localhost:8080/recipes/61a921f6028954d4f0319e6f HTTP/1.1

//**************************HEROKU**************************************

// PRODUCTION Deploy 

//Production Deploy
###
Get https://recipe-app-mandy.herokuapp.com/recipes
###
Get https://recipe-app-mandy.herokuapp.com/recipes/61a921f6028954d4f0319e6d
###

Get https://recipe-app-mandy.herokuapp.com/recipes/61a921f6028954d4f0319e6e
###
Get https://recipe-app-mandy.herokuapp.com/recipes/61a921f6028954d4f0319e6f
###


### Create contact 
POST https://recipe-app-mandy.herokuapp.com/recipes HTTP/1.1 
content-type: application/json

{
"recipeCategory":"Bailey", "recipeContributer":"Wendler", "recipeName":"bwendler@test.com", "recipeURL":"Red"
}

### PUT 
contact PUT https://recipe-app-mandy.herokuapp.com/recipes/61a921f6028954d4f0319e6f HTTP/1.1 
content-type: application/json

{
"recipeCategory":"Sandra", "recipeContributer":"Fox", "recipeName":"sfox@gmail.com", "recipeURL":"Gold"
}

### DELETE contact 
DELETE https://recipe-app-mandy.herokuapp.com/recipes/61a921f6028954d4f0319e6f HTTP/1.1




